### ISSUE TITLE
Differences between whatcd and this?

### ISSUE THREAD

**Issue by xrTor** [ApolloRIP/Gazelle#1]
what are the differences between gazelle-whatcd and this version of gazelle?

**Comment by raspbeguy** [comment]
I guess a quick look to the commits list will give you some hints.

**Comment by itismadness** [comment]
A quick look at the commits will definitely give you an idea, but the biggest thing is that the whatcd version is most likely abandoned while we'll continue to actively develop this and improve it. I'd like to continue improving the code style of Gazelle (getting rid of globals, better OOP, implement twig/blade, actual testing of the code, etc.), better tooling (Composer, Phinx, Vagrant, etc.), support of current versions of things (so PHP 7 instead of PHP 5, work on supporting strict mysql for 5.7), and of course implementing new suggestions we get from our users and fixing reported bugs.

As time goes, the differences should become increasingly apparent.

**Comment by xrTor** [comment]
can i run it on windows without VM or ubuntu OS? the what cd never ran on windows (all functionalty was unavailable)

**Comment by Athena-APL** [comment]
You cannot run this on Windows without a VM.

**Comment by itismadness** [comment]
Technically you'd probably be able to run Gazelle under Windows (crun might give you issues, but there has to be a windows replacement) and the logchecker stuff is written for specifically Debian, but you could probably adopt it. There's also probably some of the staff tools that would break. We won't (and probably never will) offer support though for people trying to run it under Windows and only really (currently) support Debian and Ubuntu.

**Comment by Urahara** [comment]
The logchecker will be someday open-source too?

**Comment by itismadness** [comment]
It's included in the repo here https://github.com/ApolloRIP/Gazelle/blob/master/classes/logchecker.class.php?
